[tool.poetry]
name = "nameguard"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
license = "../LICENSE"
packages = [{ include = "nameguard" }]


[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ens-label-inspector = { git = "https://github.com/namehash/ens-label-inspector.git", branch = "main" }
fastapi = "^0.100.1"
mangum = {version = "^0.17.0", optional = true}
web3 = "^6.9.0"
hexbytes = "^0.3.1"
httpx = "^0.24.1"
python-dotenv = "^1.0.0"


[tool.poetry.extras]
lambda = ["mangum"]


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
flake8 = "^6.1.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
pytest-asyncio = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
